### ISSUE TITLE
Procedimentos anteriores

### ISSUE THREAD

**Issue by kvnol** [adrianoavelino/livereload-gulp-php#1]
@adrianoavelino, tudo certo? Cara, eu não consigo fazer esse servidor local subir, clonei o repositório e executei exatamente como você explica. Eu preciso fazer algum procedimento anterior com Apache ou PHP?

**Comment by adrianoavelino** [comment]
Aew @kvnol ! Você está com o `gulp` instalado globalmente? É que essa é a dependência do projeto. Caso não esteja execute:  `npm install --global gulp-cli`.
Qualquer dúvida estou a disposição.

**Comment by kvnol** [comment]
E aí, @adrianoavelino. Então, tenho sim, executo o gulp com várias tarefas. Só com o connect-php que não vai. Tanto que o browser-sync funfa, mas o localhost fica só carregando.

Fiz no meu Fedora e Windows, mas nada.

**Comment by adrianoavelino** [comment]
Bom cara, aqui eu nem uso o apache. Só uso o php build, aquele da linha de comando (Ex: `php -S localhost:8000`). Você está com ele instalado aí? 
Posta o log do comando gulp aí pra ver se intendo.
_Obs: testei numa máquina windows 7 e no meu mint aqui e em ambos rodaram_

**Comment by kvnol** [comment]
Consegui rodar aqui! O problema era o php mesmo.

Valeu mesmo. :D
