### ISSUE TITLE
Tasks com mesmo nome

### ISSUE THREAD

**Issue by marcelo-ribeiro** [adrianoavelino/livereload-gulp-php#3]
Tem duas tasks com o mesmo nome. É isso mesmo? Está funcionando?

**Comment by adrianoavelino** [comment]
Realmente estão com os nomes duplicados. E o pacotes estão desatualizados e para corrigi-los dará um trabalhinho a mais. Atualmente não estou utilizando ele mais. Agora estou utilizando somente o Browsersync com o seguinte comando: `browser-sync start --proxy "http://localhost/github/reload2/" --files "*.php, *.css"`.
Na documentação tem mais algumas coisas e aqui http://blog.ti.lemaf.ufla.br/2017/06/06/browsersync/ tem um material legal também.
